// <auto-generated />
using System;
using EcoAir.EnergyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoAir.EnergyApi.Migrations
{
    [DbContext(typeof(EcoAirContext))]
    partial class EcoAirContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoAir.EnergyApi.Models.AlertaConsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeituraEnergiaId")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeConsumidoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeituraEnergiaId");

                    b.HasIndex("UnidadeConsumidoraId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("EcoAir.EnergyApi.Models.LeituraEnergia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsumoKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CustoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("FonteEnergia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeConsumidoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeConsumidoraId");

                    b.ToTable("Leituras");
                });

            modelBuilder.Entity("EcoAir.EnergyApi.Models.LimiteConsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LimiteDiarioKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LimiteMensalKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadeConsumidoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeConsumidoraId");

                    b.ToTable("Limites");
                });

            modelBuilder.Entity("EcoAir.EnergyApi.Models.UnidadeConsumidora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("EcoAir.EnergyApi.Models.AlertaConsumo", b =>
                {
                    b.HasOne("EcoAir.EnergyApi.Models.LeituraEnergia", "Leitura")
                        .WithMany()
                        .HasForeignKey("LeituraEnergiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoAir.EnergyApi.Models.UnidadeConsumidora", "Unidade")
                        .WithMany("Alertas")
                        .HasForeignKey("UnidadeConsumidoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leitura");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("EcoAir.EnergyApi.Models.LeituraEnergia", b =>
                {
                    b.HasOne("EcoAir.EnergyApi.Models.UnidadeConsumidora", "Unidade")
                        .WithMany("Leituras")
                        .HasForeignKey("UnidadeConsumidoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("EcoAir.EnergyApi.Models.LimiteConsumo", b =>
                {
                    b.HasOne("EcoAir.EnergyApi.Models.UnidadeConsumidora", "Unidade")
                        .WithMany("Limites")
                        .HasForeignKey("UnidadeConsumidoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("EcoAir.EnergyApi.Models.UnidadeConsumidora", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Leituras");

                    b.Navigation("Limites");
                });
#pragma warning restore 612, 618
        }
    }
}
